repositories/patches/rmw_cyclonedds-fix-typesupport-conditions-bug.patch, repositories/repositories.bzl
As we discuss in #1 ,the problem is solved
Fix this bug by modified [rmw_cyclonedds](https://github.com/ros2/rmw_cyclonedds/tree/foxy) package. the patch is as below based on foxy branch:
``` cpp
diff --git a/rmw_cyclonedds_cpp/src/serdata.cpp b/rmw_cyclonedds_cpp/src/serdata.cpp
index 05b3286..b3382cc 100644
--- a/rmw_cyclonedds_cpp/src/serdata.cpp
+++ b/rmw_cyclonedds_cpp/src/serdata.cpp
@@ -60,14 +60,16 @@ using ResponseTypeSupport_cpp = rmw_cyclonedds_cpp::ResponseTypeSupport<
rosidl_typesupport_introspection_cpp::ServiceMembers,
rosidl_typesupport_introspection_cpp::MessageMembers>;
-static bool using_introspection_c_typesupport(const char * typesupport_identifier)
-{
-  return typesupport_identifier == rosidl_typesupport_introspection_c__identifier;
+static bool …
```
=> Add patch to fix typesupport bug in rmw_cyclonedds.

ros2/interfaces.bzl
The previous implementation had issues with message names like MultiDOFJointState.msg, which it converted to multi_dofjoint_state.msg. This would cause a mismatch in generated and expected output names.
=> Fix the to_snake_case function

repositories/common_interfaces.BUILD.bazel
I can split this into two separate PRs if you prefer (or at least two commits in a single PR). Also, I started out with extending `ros2_interface_library` to support a `hdrs` attributes, but then realized that the not-yet-included header files are actually only useful for C++, so having the private `cpp_ros2_interface_library` and wrapping this with a `ros2_cpp_library` that includes the headers seemed like a good solution. Please let me know if you'd prefer a different approach.
=> Add visualization_msgs and fix sensor_msgs includes

repositories/geometry2.BUILD.bazel, repositories/message_filters.BUILD.bazel, repositories/ros2_repo_mappings.yaml, repositories/ros2_repositories_impl.bzl
This adds part of the geometry2 package (tf2).
File `repositories/console_bridge.BUILD.bazel` is stolen from https://github.com/mvukov/rules_ros2/compare/feature/pluginlib#diff-d1a7e3a17144dfb0f628076fc98f452c60b4d182f370b2f962ed23d518911ea1
=> Add tf2 package

repositories/common_interfaces.BUILD.bazel
When compiled with `-Wconversion`, the point cloud helpers produce some warnings. To supress them, we use `includes` instead of `strip_include_prefix`.
=> Suppress warnings from cpp_sensor_msgs

ros2/test/image_common/tests.py, ros2/test/pluginlib/tests.py
This test failed when the GTest binary fininished before we enter `TestPlugins.test_plugins()`. Adding the `keep_alive` decorator fixes that.
=> Fix flaky image_transport test

repositories/spdlog.BUILD.bazel
In QNX pthread is bundled with the rest of the libc
=> Enable building spdlog for QNX

repositories/rcutils.BUILD.bazel
In QNX dl is bundled with libc
=> Enable building rcutils for QNX

repositories/cyclonedds.BUILD.bazel
In QNX pthread is bundled with libc.
My full patch actually looks like this:
```patch
diff --git a/BUILD.bazel b/BUILD.bazel
old mode 100755
new mode 100644
index 1d33e9b..f0047f9
--- a/BUILD.bazel
+++ b/BUILD.bazel
@@ -24,6 +24,7 @@ filegroup(
cache_entries = {
"CMAKE_BUILD_TYPE": "Release",
+    "CMAKE_SYSTEM_NAME": "Foo",
"CMAKE_POSITION_INDEPENDENT_CODE": "ON",  # Must be set!
"BUILD_SHARED_LIBS": "OFF",
@@ -38,7 +39,8 @@ cache_entries = {
"ENABLE_LIFESPAN": "ON",
"ENABLE_NETWORK_PARTITIONS": "ON",
"ENABLE_SECURITY": "OFF",
-    "ENABLE_SOURCE_SPECIFIC_MULTICAST": "ON",
+    "ENABLE_SOURCE_SPECIFIC_MULTICAST": "OFF",
+    "ENABLE_IPV6": "OFF",
"ENABLE_SSL": "OFF",  # TODO(mvukov) Here we could use openssl/boringssl.
"ENABLE_TOPIC_DISCOVERY": "OFF",
"ENABLE_TYPE_DISCOVERY": "OFF",
@@ …
```
=> Enable building cyclonedds for QNX

repositories/iceoryx.BUILD.bazel
acl, rt and pthread are part of libc. At the same time we need to tell the iceoryx build system that we are building for QNX so that it doesn't try to use Linux-specific headers.
=> Enable building iceoryx for QNX

repositories/geometry2.BUILD.bazel
Python bindings are missing for `tf2_msgs`.
=> Add Python bindings to tf2_msgs

repositories/repositories.bzl
Introduced in https://github.com/mvukov/rules_ros2/pull/70
=> Fix Bazel repo name for eigen build_file

repositories/image_common.BUILD.bazel, repositories/rosbag2.BUILD.bazel
There are some visbility issues on current main:
`ERROR: /home/user/repo/pkg/BUILD:229:16: in cc_binary rule //pkg:VideoDecoderNode: target '@ros2_image_common//:image_transport_plugins_impl' is not visible from target '//pkg:VideoDecoderNode'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/user/repo/pkg/talos_video/BUILD:229:16: Analysis of target '//pkg:VideoDecoderNode' failed`
This is a follow-up fix to https://github.com/mvukov/rules_ros2/pull/86
Needed for the clangd workaround in https://github.com/mvukov/rules_ros2/issues/78
=> Make builtin ros2_plugin targets visibile

ros2/test/rosbag/publisher.cc, ros2/test/rosbag/recorder.cc, ros2/test/rosbag/tests.py
The rosbag tests are flaky, because it can happen that the recorder is
stopped before it has the required number of messages received. This is
because the process that contains the recorder has a second subscriber
that keeps track of the number of messages published. However, the
recorder's subscriber and that counting subscriber are not synchronized.
Even if the message counting subscriber has received some number of
messages, this doesn't mean that the recorder's subscriber has received
even a single message.
We fix the issue by replacing the message counting subscriber by one
that listens for bag split events. We also configure the recorder to
split bags once some number of bytes has been recorded. Once the bag
split event is received, we can be certain that the recorder has
received …
=> Use bag split as signal from recorder in rosbag tests

README.md, ros2/BUILD.bazel, ros2/ros2_node.py
```
❯ bazel run @com_github_mvukov_rules_ros2//ros2:ros2_node
INFO: Invocation ID: 4c89ed83-fd67-40a8-bd11-eadbc1da9736
INFO: Analyzed target @com_github_mvukov_rules_ros2//ros2:ros2_node (1 packages loaded, 12 targets configured).
INFO: Found 1 target...
Target @com_github_mvukov_rules_ros2//ros2:ros2_node up-to-date:
bazel-bin/external/com_github_mvukov_rules_ros2/ros2/ros2_node
INFO: Elapsed time: 0.288s, Critical Path: 0.11s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Running command line: bazel-bin/external/com_github_mvukov_rules_ros2/ros2/ros2_node
usage: ros2_node.py [-h] [--use-python-default-buffering] [--include-hidden-topics] Call `ros2 <command> -h` for more detailed usage. ...
ros2 is an extensible command-line tool for ROS 2. …
```
=> Add ros2_node cli

ros2/cc_defs.bzl, ros2/py_defs.bzl
Forgot about that one. Without this, I'm getting
```
ERROR: /home/user/repo/pkg/BUILD:30:14: //pkg:target: no such attribute 'timeout' in 'cc_binary' rule
WARNING: Target pattern parsing failed.
```
=> Also allow `timeout` attribute in ros2_py_test, ros2_cpp_test

README.md, repositories/repositories.bzl, repositories/ros2_repositories_impl.bzl
I was mostly curious about how the `bazel run //repositories/private:resolver` worked (nice one!), and what better way to try it than to actually upgrade the Humble patch release.
I checked and none of the patches are obsolete, looks like the ones that are merged upstream were not backported from rolling to humble.
=> Upgrade to release-humble-20230502

repositories/patches/rclcpp_move_ts_lib_to_publisher_base.patch, repositories/ros2_repo_mappings.yaml, repositories/ros2_repositories_impl.bzl, ros2/test/rosbag/BUILD.bazel, ros2/test/rosbag/tests.py
This adds a patch that moves the `std::shared_ptr` holding a reference to a `rclcpp::SharedLibrary` from `rclcpp::GenericPublisher` to `rclcpp::PublisherBase`. The shared library in question contains type support code for the publisher's message type. In the standard ROS build, two separate shared objects are used, one is represented by the mentioned `shared_ptr`-wrapped `SharedLibrary` instance, the other is never unloaded. At the same time, code from the latter library is required during destruction of a `PublisherBase` instance. The rules_ros2 build creates a single library, which is unloaded when `GenericPublisher` is destroyed (the `shared_ptr`'s reference count goes to zero). When `GenericPublisher`'s parent class, `PublisherBase`, is destroyed, trying to call code from the shared …
=> Add patch to move ts_lib to PublisherBase

ros2/launch.bzl, ros2/test.bzl
I have some launch files that don't directly depend on any binaries. Instead they (conditionally) include some other launch files. These should go into the ros2_launch deps I'd say.
Unfortunately currently empty nodes lists are not allowed. I don't think this restriction is necessary and can be simply removed.
Since it's a positional arg if you don't specify `nodes` Bazel will already fail with `Error: ros2_launch() missing 1 required positional argument: nodes`. I think no further check is necessary.
=> Allow empty nodes list for launch file

repositories/curl.BUILD.bazel, repositories/cyclonedds.BUILD.bazel, repositories/iceoryx.BUILD.bazel, repositories/yaml_cpp.BUILD.bazel, repositories/zstd.BUILD.bazel
See this discussion: https://github.com/mvukov/rules_ros2/discussions/154
CMAKE_BUILD_TYPE is handled internally in foreign_rules_cc:
https://github.com/bazelbuild/rules_foreign_cc/blob/816905a078773405803e86635def78b61d2f782d/foreign_cc/cmake.bzl#L208
Use `--compilation_mode=dbg` build flag to set `CMAKE_BUILD_TYPE=Debug` this also sets the other required flags for the cc compiler. `CMAKE_BUILD_TYPE=Release` is the default.
=> removed all occurences of CMAKE_BUILD_TYPE

examples/lifecycle/BUILD.bazel, ros2/launch.sh.tpl
This adds `exec` to the call of the actual binary in the launch script template. This way, no new process is created for the actual binary, but it takes the place of the wrapper script (including its PID). Without this, ROS 2 launch cannot properly communicate with the binary, as it sends signals to the wrapper script, which by default doesn't forward signals to a child process (the binary in this case).
=> Use `exec` in launch wrapper

repositories/cyclonedds.BUILD.bazel, repositories/iceoryx.BUILD.bazel, repositories/rcutils.BUILD.bazel, repositories/spdlog.BUILD.bazel
Use the same configs with QNX and it's working.
=> Support android

repositories/rosbag2.BUILD.bazel
Also make libraries public. `rosbag2_interfaces` is public, so there's
no real reason why `{cpp,py}_rosbag2_interfaces` shouldn't be.
=> Add Python target for rosbag2_interfaces

ros2/test/diagnostics/BUILD.bazel, ros2/test/diagnostics/diagnostic_publisher.cc, ros2/test/diagnostics/tests.py
We robustify this test by not relying on a bag recorder, but instead have a subscriber within the same process as the test. Since we have the messages available without extra effort, we use the chance to also check the contents of the messages.
Fixes #195.
=> Remove recorder from diagnostics test

.pre-commit-config.yaml
This makes `pre-commit` run (again) on my machine.
Before that I got
```
ERROR: npm v9.6.6 is known not to run on Node.js v12.22.9.  This version of npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
```
On a Ubuntu 22 machine.
=> Add default python and node versions in pre-commit

repositories/deps.bzl, repositories/repositories.bzl, repositories/resource_retriever.BUILD.bazel
As pointed out in https://github.com/mvukov/rules_ros2/pull/238#issuecomment-1909969580, Boost is only needed for Foxglove. It turns out it isn't actually needed there either (anymore?).
In Foxglove itself, there is only a ROS 1 Smoketest that needs boost::filesystem. So nothing we need to care about. https://github.com/search?q=repo%3Afoxglove%2Fros-foxglove-bridge%20boost&type=code
In ROS 2's resource_retriever, It seems like there was some Boost going on in the past, but on the Humble branch there definitely isn't any: https://github.com/ros/resource_retriever/blob/humble/resource_retriever/include/resource_retriever/retriever.hpp
Unless I missed something it seems to be we can just drop the dependency on Boost altogether in rules_ros2.
=> Drop dependency on Boost

examples/zero_copy/BUILD.bazel, renovate.json5, repositories/image_common.BUILD.bazel, repositories/repositories.bzl, repositories/rosbag2.BUILD.bazel, repositories/yaml-cpp.BUILD.bazel, ros2/test/BUILD.bazel, ros2/test/image_common/BUILD.bazel, ros2/test/pluginlib/BUILD.bazel, third_party/foxglove_bridge/BUILD.bazel
Extracted from / in preparation for https://github.com/mvukov/rules_ros2/pull/238
No functional or version changes in this one.
If downstream consumers of rules_ros2 depend on com_google_googletest or yaml_cpp they need to either rename their deps or properly declare their dependencies instead of relying on rules_ros2's transitive deps.
=> refactor: Rename googletest and yaml-cpp to align with bzlmod versions

repositories/geometry2.BUILD.bazel, repositories/pip_annotations.bzl, repositories/pybind11.BUILD.bazel, ros2/interfaces.bzl
`@rules_ros2_python//:python_headers` --> `@rules_python//python/cc:current_py_cc_headers`
Extracted from / in preparation for https://github.com/mvukov/rules_ros2/pull/238
Note that due to https://github.com/bazelbuild/rules_python/issues/1669 you need an up-to-date rules_python (>= 0.28.0) for this to work.
No functional or version changes in this one.
=> Use rules_python `current_py_cc_headers`

ros2/test/diagnostics/BUILD.bazel, ros2/test/diagnostics/tests.py
Extracted from / in preparation for https://github.com/mvukov/rules_ros2/pull/238
No functional or version changes in this one.
=> Make finding aggregator_node runfile bzlmod compatible

repositories/libyaml.BUILD.bazel, repositories/rcl.BUILD.bazel, repositories/repositories.bzl
libyaml was added to BCR in https://github.com/bazelbuild/bazel-central-registry/pull/1104
This PR is to update the current WORKSPACE version to use the same BUILD and target name.
The source URL also changed to the release artifact. The commit we're currently pointing at is literally the 0.2.5 tag, but the release artifact has a slightly different structure. That's why there is no expand_template anymore.
=> Use bzlmod-compatible libyaml release

renovate.json5, repositories/asio.BUILD.bazel, repositories/curl.BUILD.bazel, repositories/repositories.bzl
We're using BoringSSL, not OpenSSL. Need to update the lib name to be compatible with the BCR boringssl version.
=> Refactor ssl lib name

WORKSPACE, examples/WORKSPACE, repositories/repositories.bzl
Extracted from / in preparation for https://github.com/mvukov/rules_ros2/pull/238
No functional or version changes in this one. Only the WORKSPACE incantation changes.
=> refactor: extract rules_ros2_workspace_deps

repositories/ros2_repo_mappings.yaml, repositories/ros2_repositories_impl.bzl
Fix issue where `iceoryx` is being pulled down as version 2.0.5, but we are stripping 2.0.3, which causes build errors like `Prefix "iceoryx-2.0.3" was given, but not found in the archive. Here are possible prefixes for this archive: "iceoryx-2.0.5".`  This changed the version that is being stripped from 2.0.3 to 2.0.5.
=> Fix stripped prefix of iceoryx

ros2/ament.bzl
Split off https://github.com/mvukov/rules_ros2/pull/238
=> allow `flaky` `ros2_cpp_test`s

examples/chatter/talker.rs, examples/zero_copy/listener.rs, examples/zero_copy/talker.rs, repositories/patches/ros2_rust_logging.patch, repositories/ros2_rust.BUILD.bazel, repositories/rust_setup_stage_1.bzl, ros2/test/rust/publisher.rs, third_party/ros2_rust_logging/BUILD.bazel, third_party/ros2_rust_logging/logging.rs
Adds logging to ros2_rust. Since rcl_bindings is private to rlcrs I had to inject logging.rs to rclrs build. The logging functionality should eventually live in ros2_rust repo.
=> Add logging to ros2_rust

repositories/cyclonedds.BUILD.bazel, repositories/iceoryx.BUILD.bazel
#165 added support for Android, and correctly combined a lot of settings with the QNX platform. However, it also started passing `CMAKE_SYSTEM_NAME=ANDROID_OR_QNX` to CMake, which is not a supported value. Instead pass `Android` or `QNX` depending on the current platform (see docs [here](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_NAME.html)).
I had to re-organize a few config settings and some groups of flags passed together, but functionally the `CMAKE_SYSTEM_NAME` is the only value that's now passed different for the `Android` and `QNX` platform.
=> fix CMAKE_SYSTEM_NAME for Android and QNX

ros2/interfaces.bzl
See https://github.com/bazelbuild/bazel/commit/8f18d362c852377740cb032b02c42d78b9a44ad0. This is the default in Bazel 8.
=> Prepare for `--incompatible_struct_has_no_methods` switch

repositories/asio.BUILD.bazel, repositories/foxglove_bridge.BUILD.bazel, repositories/repositories.bzl
Upgrade 3rd party deps to prepare Bzlmod compatibility.
Split off https://github.com/mvukov/rules_ros2/pull/238
=> Upgrade 3rd party deps to prepare Bzlmod compat

repositories/rosbag2.BUILD.bazel
Though not used from Python code, in the C++ bindings `rclpy.duration` is [imported](https://github.com/ros2/rosbag2/blob/humble/rosbag2_py/src/rosbag2_py/_storage.cpp#L35). This showed when migrating to the bzlmod branch. Not sure why it didn't show up before. Probably because there was some `rclpy` dep elsewhere.
=> fix: add rclpy dependency to rosbag2_py

repositories/diagnostics.BUILD.bazel, repositories/rpyutils.BUILD.bazel
When depending on rules_ros2 libraries from [rules_py](https://github.com/aspect-build/rules_py)'s rules, `rpyutils` is not on the path. For `diagnostic_updater`, the required import path even with `rules_python` is `diagnostic_updater.diagnostic_updater`, when it should only be `diagnostic_updater`. Adding the import to each `py_library` fixes this.
=> Add missing imports for py_libraries

repositories/patches/rclcpp_do-not-allocate-in-signal-handler.patch, repositories/ros2_repositories_impl.bzl
The RCLCPP_INFO causes allocations (due to libfmt iirc) that may (and has) lead to deadlocks.
See https://developer.arm.com/documentation/101136/22-1-3/General-troubleshooting/Memory-debugging/Deadlock-when-calling-printf-or-malloc-from-a-signal-handler
=> Patch rclcpp to not allocate in signal handlers

WORKSPACE.bzlmod
This is used when running with "--enable_bzlmod" and "--enable_workspace" (default in Bazel 7).
=> Add WORKSPACE.bzlmod

repositories/cyclonedds.BUILD.bazel
The CMake build of CycloneDDS is causing nondeterminism in our build (i.e. rebuilding build artifacts causes hash changes).
Disabling LTO on the CycloneDDS CMake build helps with this.
=> Disable CycloneDDS LTO

MODULE.bazel, repositories/repositories.bzl
This requires an update of the `xacro` dependency.
=> Add support for Python 3.13

ros2/py_defs.bzl
This is what I had in mind. I can add an example where we use `rules_py`, but wasn't sure whether pulling in `rules_py` just for this is justified.
Fixes #458
=> Allow customization of underlying rule in `ros2_py_{binary,test}`

.bazelrc, repositories/clang_configure.bzl, ros2/ament.bzl, ros2/cc_defs.bzl, ros2/interfaces.bzl, ros2/py_defs.bzl, ros2/rust_defs.bzl, ros2/test/pluginlib/BUILD.bazel
The native ones are deprecated and will be removed in a future Bazel version.
=> Explicitly load rules
